// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qxzlkesybpmiqjolduih.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF4emxrZXN5YnBtaXFqb2xkdWloIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU0NjUxODMsImV4cCI6MjA3MTA0MTE4M30.TF3TLOvHk-Q2IF2ZI_0lwXd1NJ6QCq_Hz7_V8eXlsF0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});